#Requires -RunAsAdministrator
<#
.SYNOPSIS
    Applies maximum lockdown hardening for a kiosk, thin client, or guard terminal.

.DESCRIPTION
    Designed for single-purpose machines: guard terminals, reception kiosks, lobby
    access control consoles, operator display stations. Everything that can be
    disabled is disabled. Assumes the machine runs one application and operators
    should not be able to deviate from that.

    Key decisions:
      RDP is DISABLED. No remote administration on a kiosk -- physical access only.
      NetBIOS and LLMNR are DISABLED. IPv6 is set to prefer IPv4. Kiosks do not need them.
      UAC is set to Always Notify. Any elevation on a kiosk should be conspicuous.
      WSH is DISABLED. No script execution of any kind on a locked-down machine.
      High Performance power plan is ON. Kiosks run 24/7, throttling is wrong.
      Hibernation is DISABLED. Kiosks must never sleep or hibernate.
      All consumer apps are removed. Clean OS only.
      BitLocker is enabled. Physical access must not yield data access.
      Removable storage is denied machine-wide.
      With -KioskApp and -KioskUser, Explorer is replaced by the kiosk app as that
      account's shell, and Task Manager, lock, log off, Run, and Control Panel are
      disabled for it. Without those parameters the machine is hardened but not kiosked.

.NOTES
    ================================================================
    Study Workstation Configurator
    Template: Kiosk / Thin Client / Guard Terminal

    Generated by Hans Study, CISSP
    Generated:          2026-05-16
    Config fingerprint: (curated baseline; not configurator output)

    Website:   https://hans.study
    Email:     contact@hans.study
    LinkedIn:  https://linkedin.com/in/hans-study
    Instagram: https://instagram.com/studybyt3s
    X:         https://x.com/studybyt3s
    YouTube:   https://youtube.com/@studybyt3s
    GitHub:    https://github.com/hansstudy

    Target OS:  Windows 10/11 Pro or Enterprise
    Version:    2.0

    STANDARDS REFERENCED:
      DISA STIG Windows 11 V2R2 / Windows 10 V2R7 (public.cyber.mil)
      CIS Microsoft Windows 11 Benchmark Level 2   (cisecurity.org)
      NSA/CISA Cybersecurity Information Sheets    (media.defense.gov)
      CSE/CCCS ITSP.70.012                         (cyber.gc.ca)

    Source-available. Personal and internal use permitted.
    Redistribution requires written authorization from Hans Study.
    See LICENSE for full terms.
    Test against your kiosk application before production deployment.
    Hans Study accepts no liability for unintended consequences.
    ================================================================
#>

[CmdletBinding()]
param(
    # Full path to the kiosk application executable. When supplied together with
    # -KioskUser, the app is allow-listed in Controlled Folder Access and becomes
    # that account's shell in place of Explorer.
    [string]$KioskApp,

    # Local standard-user account the kiosk runs as. Created if missing (you are
    # prompted for a password). The script refuses to proceed if it is an administrator.
    [string]$KioskUser
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Continue"
$SkippedEntControls = [System.Collections.Generic.List[string]]::new()

$LogDate = Get-Date -Format "yyyyMMdd"
$LogPath = "C:\Logs\Kiosk-ThinClient-Lockdown_$LogDate.log"
if (-not (Test-Path "C:\Logs")) { New-Item -ItemType Directory -Path "C:\Logs" -Force | Out-Null }
Start-Transcript -Path $LogPath -Append -IncludeInvocationHeader | Out-Null

# Helper functions are embedded here so the script runs standalone with no module dependency.
function Write-TSGSection { param([string]$Title, [string]$Subtitle = "")
    Write-Host ""; Write-Host "  == $Title" -ForegroundColor Yellow
    if ($Subtitle) { Write-Host "     $Subtitle" -ForegroundColor DarkGray }
}
function Set-TSGRegistry { param([string]$Path, [string]$Name, [object]$Value, [string]$Type = "DWord")
    try {
        if (-not (Test-Path $Path)) { New-Item -Path $Path -Force | Out-Null }
        Set-ItemProperty -Path $Path -Name $Name -Value $Value -Type $Type -Force -ErrorAction Stop
        Write-Host "    [OK] $($Path.Split('\')[-1])\$Name = $Value" -ForegroundColor Green
    } catch { Write-Host "    [FAIL] $Name -- $($_.Exception.Message)" -ForegroundColor Red }
}
function Remove-TSGAppx { param([string]$PackageName, [string]$FriendlyName)
    try {
        Get-AppxProvisionedPackage -Online -ErrorAction SilentlyContinue |
            Where-Object { $_.DisplayName -like "*$PackageName*" } |
            Remove-AppxProvisionedPackage -Online -ErrorAction SilentlyContinue | Out-Null
        Get-AppxPackage -AllUsers -ErrorAction SilentlyContinue |
            Where-Object { $_.Name -like "*$PackageName*" } |
            Remove-AppxPackage -AllUsers -ErrorAction SilentlyContinue
        Write-Host "    [OK] $FriendlyName removed or already absent" -ForegroundColor Green
    } catch { Write-Host "    [SKIP] $FriendlyName" -ForegroundColor DarkGray }
}
function Test-TSGEnterprise { param([string]$ControlName = "This control")
    $sku = (Get-CimInstance Win32_OperatingSystem).OperatingSystemSKU
    if ($sku -in @(4,27,70,84,121,122,125,126,7,8,12,13,79,80)) { return $true }
    Write-Host "    [SKIP] $ControlName requires Enterprise license (SKU: $sku)" -ForegroundColor DarkGreen
    $script:SkippedEntControls.Add($ControlName); return $false
}
function New-TSGRestorePoint { param([string]$Description = "Hardening")
    try { Checkpoint-Computer -Description "$Description $(Get-Date -Format 'yyyy-MM-dd')" -RestorePointType "MODIFY_SETTINGS" -ErrorAction Stop
          Write-Host "  [OK] Restore point created" -ForegroundColor Green }
    catch { Write-Host "  [WARN] Restore point failed -- continuing" -ForegroundColor Yellow }
}
function Disable-TSGNetBIOS {
    try {
        $adapters = Get-WmiObject -Class Win32_NetworkAdapterConfiguration -Filter "IPEnabled = True"
        foreach ($a in $adapters) { $a.SetTcpipNetbios(2) | Out-Null }
        Write-Host "    [OK] NetBIOS over TCP/IP disabled on all adapters" -ForegroundColor Green
    } catch { Write-Host "    [FAIL] $($_.Exception.Message)" -ForegroundColor Red }
}

Write-Host ""
Write-Host "  =========================================================" -ForegroundColor DarkYellow
Write-Host "  Kiosk / Thin Client / Guard Terminal Lockdown" -ForegroundColor DarkYellow
Write-Host "  Maximum restriction for single-purpose Windows deployments" -ForegroundColor Gray
Write-Host "  Hans Study, CISSP | https://hans.study" -ForegroundColor DarkGray
Write-Host "  Log: $LogPath" -ForegroundColor DarkGray
Write-Host "  =========================================================" -ForegroundColor DarkYellow
Write-Host ""

$OsSku = (Get-CimInstance Win32_OperatingSystem).OperatingSystemSKU
$IsEnterprise = $OsSku -in @(4,27,70,84,121,122,125,126,7,8,12,13,79,80)
Write-Host "  OS SKU: $OsSku | Edition: $(if ($IsEnterprise) { 'Enterprise/Server' } else { 'Pro' })" `
    -ForegroundColor $(if ($IsEnterprise) { "Green" } else { "Yellow" })
Write-Host ""

New-TSGRestorePoint -Description "Kiosk / Thin Client Lockdown"


# ================================================================================
# CREDENTIAL AND IDENTITY PROTECTION
# Source: DISA WN11-CC-000038 | WN11-SO-000100/195/205 | WN11-00-000095
# ================================================================================
Write-TSGSection "CREDENTIAL AND IDENTITY PROTECTION" "DISA WN11-CC-000038 | WN11-SO-000100/195/205"

Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\WDigest" -Name "UseLogonCredential" -Value 0  # WN11-CC-000038
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Lsa" -Name "NoLMHash"           -Value 1                         # WN11-SO-000195
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Lsa" -Name "LmCompatibilityLevel" -Value 5                       # WN11-SO-000205
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Lsa" -Name "RunAsPPL"           -Value 1                         # WN11-SO-000100
Write-Host "    [NOTE] Restart required for LSA Protection" -ForegroundColor Yellow

if (Test-TSGEnterprise -ControlName "Credential Guard (WN11-00-000095)") {
    Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\DeviceGuard" -Name "EnableVirtualizationBasedSecurity" -Value 1
    Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\DeviceGuard" -Name "RequirePlatformSecurityFeatures"   -Value 1
    Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\DeviceGuard\Scenarios\CredentialGuard" -Name "Enabled" -Value 1
    Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Lsa" -Name "LsaCfgFlags" -Value 1
    Write-Host "    [NOTE] Restart required for Credential Guard" -ForegroundColor Yellow
}


# ================================================================================
# NETWORK HARDENING -- MAXIMUM RESTRICTION
# Source: DISA WN11-00-000155/160/165 | WN11-CC-000080/085 | WN11-NX | WN11-SO-000160/165
# ================================================================================
Write-TSGSection "NETWORK HARDENING -- MAXIMUM RESTRICTION" "DISA WN11-00-000155/160/165 | WN11-CC-000080/085"

Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters" -Name "SMB1" -Value 0                  # WN11-00-000165
Disable-WindowsOptionalFeature -Online -FeatureName "SMB1Protocol" -NoRestart -ErrorAction SilentlyContinue | Out-Null
Write-Host "    [OK] SMBv1 disabled" -ForegroundColor Green

Disable-WindowsOptionalFeature -Online -FeatureName "MicrosoftWindowsPowerShellV2Root" -NoRestart -ErrorAction SilentlyContinue | Out-Null
Write-Host "    [OK] PowerShell v2 removed" -ForegroundColor Green

Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient" -Name "EnableMulticast" -Value 0                 # WN11-CC-000085

Disable-TSGNetBIOS  # WN11-CC-000080

# Prefer IPv4 over IPv6 -- kiosk machines do not need IPv6, reduces attack surface
# Source: NSA IPv6 guidance | CCCS ITSP.70.012
# DisabledComponents = 0x20 prefers IPv4 over IPv6 (Microsoft-recommended). 0xFF also kills loopback and adds a 5-second boot delay.
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters" -Name "DisabledComponents" -Value 32
Write-Host "    [OK] IPv6 set to prefer IPv4 (restart required)" -ForegroundColor Green

Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled True
Set-NetFirewallProfile -Profile Domain,Public,Private -DefaultInboundAction Block
Write-Host "    [OK] Firewall enabled, default-deny inbound" -ForegroundColor Green

Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters"    -Name "RequireSecuritySignature" -Value 1  # WN11-SO-000160
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters" -Name "RequireSecuritySignature" -Value 1  # WN11-SO-000165


# ================================================================================
# WINDOWS DEFENDER
# Source: DISA WN11-00-000270/275
# ================================================================================
Write-TSGSection "WINDOWS DEFENDER" "DISA WN11-00-000270/275"

Set-Service -Name "WinDefend" -StartupType Automatic -ErrorAction SilentlyContinue
Start-Service -Name "WinDefend" -ErrorAction SilentlyContinue
Set-MpPreference -DisableRealtimeMonitoring $false
Set-MpPreference -EnableNetworkProtection Enabled

# Enable Controlled Folder Access. The kiosk app is allow-listed in the KIOSK MODE
# section below when -KioskApp is supplied; without it, CFA will block the app from
# Documents, Desktop, and Pictures on first run.
Set-MpPreference -EnableControlledFolderAccess Enabled
Write-Host "    [OK] Defender with CFA enabled (anti-ransomware)" -ForegroundColor Green


# ================================================================================
# AUDIT POLICY AND LOGGING
# Source: DISA WN11-AU | NSA/CISA June 2022 CSI | CCCS ITSP.70.012
# ================================================================================
Write-TSGSection "AUDIT POLICY AND LOGGING" "DISA WN11-AU-000010 through WN11-AU-000560"

AuditPol /set /subcategory:"Logon"                   /success:enable /failure:enable | Out-Null
AuditPol /set /subcategory:"Logoff"                  /success:enable                 | Out-Null
AuditPol /set /subcategory:"Account Lockout"         /failure:enable                 | Out-Null
AuditPol /set /subcategory:"Credential Validation"   /success:enable /failure:enable | Out-Null
AuditPol /set /subcategory:"Process Creation"        /success:enable                 | Out-Null
AuditPol /set /subcategory:"Audit Policy Change"     /success:enable /failure:enable | Out-Null
AuditPol /set /subcategory:"User Account Management" /success:enable /failure:enable | Out-Null
Write-Host "    [OK] Audit policy configured" -ForegroundColor Green

Set-TSGRegistry -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\Audit" -Name "ProcessCreationIncludeCmdLine_Enabled" -Value 1

wevtutil sl Security    /ms:1073741824 | Out-Null   # 1 GB
wevtutil sl Application /ms:268435456  | Out-Null   # 256 MB
wevtutil sl System      /ms:268435456  | Out-Null   # 256 MB
Write-Host "    [OK] Log sizes: Security 1GB" -ForegroundColor Green

Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\ScriptBlockLogging" -Name "EnableScriptBlockLogging"         -Value 1
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\ScriptBlockLogging" -Name "EnableScriptBlockInvocationLogging" -Value 1
wevtutil sl "Microsoft-Windows-PowerShell/Operational" /ms:104857600 | Out-Null
Write-Host "    [OK] PS Script Block Logging enabled" -ForegroundColor Green


# ================================================================================
# ACCESS CONTROL -- MAXIMUM RESTRICTION
# Source: DISA WN11-SO-000245/250 | WN11-CC-000020/030/150 | WN11-00-000030
# ================================================================================
Write-TSGSection "ACCESS CONTROL -- MAXIMUM RESTRICTION" "DISA WN11-SO-000245/250 | WN11-CC-000020/030/150"

# UAC -- Always Notify (ConsentPromptBehaviorAdmin = 2)
# Any elevation attempt on a kiosk should be conspicuous and require admin interaction
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" -Name "EnableLUA"                 -Value 1
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" -Name "PromptOnSecureDesktop"      -Value 1
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" -Name "ConsentPromptBehaviorAdmin" -Value 2

# Standard user elevation blocked (ConsentPromptBehaviorUser = 0 = auto-deny)
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" -Name "ConsentPromptBehaviorUser"  -Value 0

# Disable AutoRun on all drive types
# Source: DISA WN11-CC-000150 | CIS 18.9.8.1 | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer" -Name "NoDriveTypeAutoRun" -Value 255

# Disable RDP -- no remote administration on a kiosk, physical access only
# Source: DISA WN11-CC-000020 | CIS 18.9.59.2 | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 1
Disable-NetFirewallRule -DisplayGroup "Remote Desktop" -ErrorAction SilentlyContinue
Write-Host "    [OK] RDP disabled" -ForegroundColor Green

# NLA still enforced even with RDP disabled -- belt and suspenders
# Source: DISA WN11-CC-000030 | CIS 18.9.59.2.1 | CCCS
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -Name "UserAuthentication" -Value 1

# Enable BitLocker -- physical access to a kiosk must not yield data access
# Available on Pro and Enterprise. Requires TPM.
# Source: DISA WN11-00-000030 | NSA | CCCS ITSP.70.012
Write-Host "    Enabling BitLocker on C: ..." -ForegroundColor DarkGray
$tpm = Get-Tpm -ErrorAction SilentlyContinue
if ($tpm -and $tpm.TpmPresent -and $tpm.TpmReady) {
    manage-bde -on C: -RecoveryPassword -SkipHardwareTest | Out-Null
    if ($LASTEXITCODE -eq 0) {
        Write-Host "    [OK] BitLocker enabled on C:. Recovery key was NOT written to this log." -ForegroundColor Green
        Write-Host "    [NOTE] Retrieve and escrow the key now: manage-bde -protectors -get C:" -ForegroundColor Yellow
    } else {
        Write-Host "    [FAIL] manage-bde exit code $LASTEXITCODE (already encrypted, feature missing, or blocked by policy)" -ForegroundColor Red
    }
} else {
    Write-Host "    [SKIP] No ready TPM detected. Enable BitLocker manually with a startup key or password protector." -ForegroundColor DarkGreen
}
Write-Host "    [NOTE] Restart required to complete encryption." -ForegroundColor Yellow

# Restrict PowerShell execution policy to RemoteSigned
Set-ExecutionPolicy RemoteSigned -Scope LocalMachine -Force

# Block Office macros from internet sources
$officeVersion = "16.0"
foreach ($app in @("Word", "Excel", "PowerPoint", "Outlook", "Access")) {
    Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Office\$officeVersion\$app\Security" -Name "blockcontentexecutionfrominternet" -Value 1
}

# Disable Windows Script Host -- no script execution on a kiosk
# Source: NSA | CCCS ITSP.70.012
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Microsoft\Windows Script Host\Settings" -Name "Enabled" -Value 0
Write-Host "    [WARN] WSH disabled -- no .vbs or .js execution permitted" -ForegroundColor Yellow

# AppLocker -- Enterprise/Education only, starts the service
# Rule configuration via Group Policy is required separately
# Source: DISA STIG | CIS L2 | NSA/CISA | CCCS ITSP.70.012
if (Test-TSGEnterprise -ControlName "AppLocker") {
    sc.exe config appidsvc start= auto | Out-Null
    Start-Service -Name "AppIDSvc" -ErrorAction SilentlyContinue
    Write-Host "    [OK] AppIDSvc enabled -- configure AppLocker rules via Group Policy" -ForegroundColor Green
}

Write-Host "    [OK] Access control applied" -ForegroundColor Green


# ================================================================================
# TELEMETRY AND PRIVACY
# Source: DISA WN11-CC-000010/206/225 | NSA/CISA | CCCS | PIPEDA
# ================================================================================
Write-TSGSection "TELEMETRY AND PRIVACY" "DISA WN11-CC-000010/206/225"

# DiagTrack service left running. Disabling it breaks the Defender for Endpoint sensor.
# The AllowTelemetry policy above controls the data level; the service itself must stay.
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\DataCollection" -Name "AllowTelemetry" -Value 0
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection" -Name "AllowTelemetry" -Value 0
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\System" -Name "PublishUserActivities" -Value 0
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\System" -Name "UploadUserActivities"  -Value 0
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsAI" -Name "DisableAIDataAnalysis" -Value 1
Disable-WindowsOptionalFeature -Online -FeatureName "Recall" -NoRestart -ErrorAction SilentlyContinue | Out-Null
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\AdvertisingInfo" -Name "DisabledByGroupPolicy" -Value 1
Write-Host "    [OK] Telemetry, Recall, Advertising ID disabled" -ForegroundColor Green


# ================================================================================
# PERFORMANCE TUNING -- KIOSK RUNS 24/7
# Kiosks need consistent performance, not power management tradeoffs.
# ================================================================================
Write-TSGSection "PERFORMANCE TUNING -- 24/7 OPERATION" "best practice"

# High Performance power plan -- prevents CPU P-state throttling
# GUID 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c is the built-in High Performance plan
$highPerfGuid = "8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c"
powercfg -setactive $highPerfGuid 2>$null
if ($LASTEXITCODE -ne 0) {
    # Plan may have been removed by OEM imaging -- duplicate and activate it
    powercfg -duplicatescheme $highPerfGuid | Out-Null
    powercfg -setactive $highPerfGuid | Out-Null
}
Write-Host "    [OK] Power plan: High Performance" -ForegroundColor Green

# Disable hibernation -- kiosks must never hibernate
# Hibernate causes a cold-start reconnect cycle that disrupts kiosk application state
powercfg -h off
Write-Host "    [OK] Hibernation disabled" -ForegroundColor Green

# Disable SysMain (Superfetch) -- no benefit on a fixed-workload 24/7 machine
Stop-Service -Name "SysMain" -ErrorAction SilentlyContinue
Set-Service  -Name "SysMain" -StartupType Disabled
Write-Host "    [OK] SysMain (Superfetch) disabled" -ForegroundColor Green

# Disable Windows Search Indexing -- kiosks do not use Windows Search
Stop-Service -Name "WSearch" -ErrorAction SilentlyContinue
Set-Service  -Name "WSearch" -StartupType Disabled
Write-Host "    [OK] Windows Search Indexing disabled" -ForegroundColor Green


# ================================================================================
# EXPLOIT MITIGATION
# Source: DISA WN11-00-000145/150 | NSA | CCCS ITSP.70.012
# ================================================================================
Write-TSGSection "EXPLOIT MITIGATION" "DISA WN11-00-000145/150"

bcdedit /set nx AlwaysOn | Out-Null
Write-Host "    [OK] DEP set to AlwaysOn (restart required)" -ForegroundColor Green

Set-ProcessMitigation -System -Enable BottomUp,HighEntropy -ErrorAction SilentlyContinue
Write-Host "    [OK] ASLR bottom-up and high-entropy enabled" -ForegroundColor Green

# Value 0 ENABLES SEHOP (counterintuitive registry name, confirmed in DISA WN11-00-000150)
Set-TSGRegistry -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\kernel" -Name "DisableExceptionChainValidation" -Value 0


# ================================================================================
# BLOATWARE REMOVAL -- COMPLETE
# ================================================================================
Write-TSGSection "BLOATWARE REMOVAL -- COMPLETE" "Least functionality | DISA CM controls"

Remove-TSGAppx -PackageName "Microsoft.549981C3F5F10"                -FriendlyName "Cortana"
Remove-TSGAppx -PackageName "Microsoft.Windows.Copilot"              -FriendlyName "Windows Copilot"
Remove-TSGAppx -PackageName "MicrosoftWindows.Client.WebExperience"  -FriendlyName "Windows Widgets"
Remove-TSGAppx -PackageName "Microsoft.BingNews"                     -FriendlyName "Bing News"
Remove-TSGAppx -PackageName "Microsoft.BingWeather"                  -FriendlyName "Bing Weather"
Remove-TSGAppx -PackageName "Microsoft.GamingApp"                    -FriendlyName "Xbox Gaming App"
Remove-TSGAppx -PackageName "Microsoft.XboxApp"                      -FriendlyName "Xbox App"
Remove-TSGAppx -PackageName "Microsoft.XboxGameOverlay"              -FriendlyName "Xbox Game Overlay"
Remove-TSGAppx -PackageName "Microsoft.XboxGamingOverlay"            -FriendlyName "Xbox Gaming Overlay"
Remove-TSGAppx -PackageName "Microsoft.Xbox.TCUI"                    -FriendlyName "Xbox TCUI"
Remove-TSGAppx -PackageName "Microsoft.MicrosoftSolitaireCollection" -FriendlyName "Microsoft Solitaire"
Remove-TSGAppx -PackageName "Microsoft.MixedReality.Portal"          -FriendlyName "Mixed Reality Portal"
Remove-TSGAppx -PackageName "Clipchamp.Clipchamp"                    -FriendlyName "Clipchamp"
Remove-TSGAppx -PackageName "microsoft.windowscommunicationsapps"    -FriendlyName "Mail and Calendar"
Remove-TSGAppx -PackageName "Microsoft.People"                       -FriendlyName "People App"
Remove-TSGAppx -PackageName "Microsoft.WindowsMaps"                  -FriendlyName "Windows Maps"
Remove-TSGAppx -PackageName "Microsoft.MSPaint"                      -FriendlyName "Paint 3D"
Remove-TSGAppx -PackageName "Microsoft.SkypeApp"                     -FriendlyName "Skype"
Remove-TSGAppx -PackageName "MicrosoftTeams"                         -FriendlyName "Teams Consumer"
Remove-TSGAppx -PackageName "Microsoft.YourPhone"                    -FriendlyName "Phone Link"
Remove-TSGAppx -PackageName "MicrosoftCorporationII.QuickAssist"     -FriendlyName "Quick Assist"
Remove-TSGAppx -PackageName "Microsoft.WindowsFeedbackHub"           -FriendlyName "Feedback Hub"
Remove-TSGAppx -PackageName "Microsoft.Todos"                        -FriendlyName "Microsoft To Do"
Remove-TSGAppx -PackageName "Microsoft.PowerAutomateDesktop"         -FriendlyName "Power Automate Desktop"
Remove-TSGAppx -PackageName "BytedancePte.TikTok"                    -FriendlyName "TikTok"

Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\CloudContent" -Name "DisableWindowsConsumerFeatures" -Value 1
Write-Host "    [OK] All consumer apps and Start Menu ads removed" -ForegroundColor Green


# ================================================================================
# KIOSK MODE -- SINGLE-APPLICATION SHELL
# Hardening alone leaves Explorer, Task Manager, and the Start menu reachable.
# This section denies removable storage for everyone and, when -KioskApp and
# -KioskUser are supplied, turns the machine into a single-app kiosk for that account.
# Source: Microsoft "Set up a single-app kiosk" | CIS Windows 11 L2 removable storage
# ================================================================================
Write-TSGSection "KIOSK MODE -- SINGLE-APPLICATION SHELL" "Requires -KioskApp and -KioskUser for the shell lock"

# Removable storage denied machine-wide. A guard terminal has no business mounting USB mass storage.
Set-TSGRegistry -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\RemovableStorageDevices" -Name "Deny_All" -Value 1
Write-Host "    [OK] All removable storage classes denied (restart required)" -ForegroundColor Green

if (-not $KioskApp -or -not $KioskUser) {
    Write-Host "    [NOTE] -KioskApp and -KioskUser were not supplied. The machine is hardened but Explorer" -ForegroundColor Yellow
    Write-Host "           remains the shell. Re-run with both to lock one app to one account:" -ForegroundColor Yellow
    Write-Host "           .\Kiosk-ThinClient-Lockdown.ps1 -KioskApp 'C:\Kiosk\App.exe' -KioskUser 'kiosk'" -ForegroundColor DarkGray
}
else {
    $kioskOk = $true

    if (-not (Test-Path -LiteralPath $KioskApp -PathType Leaf)) {
        Write-Host "    [FAIL] -KioskApp not found: $KioskApp" -ForegroundColor Red
        $kioskOk = $false
    }

    $acct = Get-LocalUser -Name $KioskUser -ErrorAction SilentlyContinue
    if (-not $acct) {
        Write-Host "    Creating local user '$KioskUser'. Enter a password at the prompt." -ForegroundColor DarkGray
        try {
            $pw = Read-Host -AsSecureString "    Password for $KioskUser"
            $acct = New-LocalUser -Name $KioskUser -Password $pw -PasswordNeverExpires -UserMayNotChangePassword -ErrorAction Stop
            Write-Host "    [OK] Local user '$KioskUser' created" -ForegroundColor Green
        } catch {
            Write-Host "    [FAIL] Could not create '$KioskUser': $($_.Exception.Message)" -ForegroundColor Red
            $kioskOk = $false
        }
    }

    if ($acct) {
        $isAdmin = Get-LocalGroupMember -Group "Administrators" -ErrorAction SilentlyContinue | Where-Object { $_.SID -eq $acct.SID }
        if ($isAdmin) {
            Write-Host "    [FAIL] '$KioskUser' is a member of Administrators. A kiosk account must be a standard user." -ForegroundColor Red
            $kioskOk = $false
        }
    }

    if ($kioskOk) {
        # CFA must trust the kiosk app or it cannot write to Documents, Desktop, or Pictures.
        Add-MpPreference -ControlledFolderAccessAllowedApplications $KioskApp -ErrorAction SilentlyContinue
        Write-Host "    [OK] Controlled Folder Access allow-list: $KioskApp" -ForegroundColor Green

        # Load the kiosk user's hive so per-user policy lands even if the account has never logged on.
        $sid = $acct.SID.Value
        $hiveKey = "HKU\$sid"
        $hiveLoaded = $false
        if (-not (Test-Path "Registry::$hiveKey")) {
            $profilePath = (Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProfileList\$sid" -ErrorAction SilentlyContinue).ProfileImagePath
            if (-not $profilePath) { $profilePath = "C:\Users\$KioskUser" }
            $ntuser = Join-Path $profilePath "NTUSER.DAT"
            if (Test-Path -LiteralPath $ntuser) {
                reg.exe load $hiveKey $ntuser | Out-Null
                $hiveLoaded = ($LASTEXITCODE -eq 0)
            }
        }

        if (Test-Path "Registry::$hiveKey") {
            $u = "Registry::$hiveKey"
            # Replace Explorer with the kiosk app as this account's shell.
            Set-TSGRegistry -Path "$u\Software\Microsoft\Windows NT\CurrentVersion\Winlogon" -Name "Shell" -Value $KioskApp -Type String
            # Remove every escape hatch a standard user could reach from the kiosk app.
            Set-TSGRegistry -Path "$u\Software\Microsoft\Windows\CurrentVersion\Policies\System"   -Name "DisableTaskMgr"         -Value 1
            Set-TSGRegistry -Path "$u\Software\Microsoft\Windows\CurrentVersion\Policies\System"   -Name "DisableLockWorkstation" -Value 1
            Set-TSGRegistry -Path "$u\Software\Microsoft\Windows\CurrentVersion\Policies\System"   -Name "DisableChangePassword"  -Value 1
            Set-TSGRegistry -Path "$u\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer" -Name "NoLogoff"               -Value 1
            Set-TSGRegistry -Path "$u\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer" -Name "NoClose"                -Value 1
            Set-TSGRegistry -Path "$u\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer" -Name "NoRun"                  -Value 1
            Set-TSGRegistry -Path "$u\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer" -Name "NoControlPanel"         -Value 1
            Set-TSGRegistry -Path "$u\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer" -Name "NoDriveTypeAutoRun"     -Value 255
            # Operator-facing settings that belong in the kiosk account, not the admin's.
            Set-TSGRegistry -Path "$u\Software\Microsoft\Windows\CurrentVersion\Explorer\VisualEffects"    -Name "VisualFXSetting"              -Value 2
            Set-TSGRegistry -Path "$u\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" -Name "SubscribedContentEnabled"     -Value 0
            Set-TSGRegistry -Path "$u\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" -Name "SystemPaneSuggestionsEnabled" -Value 0
            Write-Host "    [OK] '$KioskUser' shell is now the kiosk app. Task Manager, lock, log off, Run, Control Panel disabled." -ForegroundColor Green
        } else {
            Write-Host "    [FAIL] Registry hive for '$KioskUser' is not available. Log on as that user once, log off, then re-run." -ForegroundColor Red
        }

        if ($hiveLoaded) { [gc]::Collect(); reg.exe unload $hiveKey | Out-Null }

        if ($IsEnterprise) {
            Write-Host "    [NOTE] Enterprise detected. Microsoft's supported path for Win32 kiosks is Shell Launcher v2:" -ForegroundColor Yellow
            Write-Host "           Enable-WindowsOptionalFeature -Online -FeatureName Client-EmbeddedShellLauncher" -ForegroundColor DarkGray
            Write-Host "           The per-user shell set above works on Pro and Enterprise and needs no feature install." -ForegroundColor DarkGray
        }
        Write-Host "    [NOTE] For unattended boot, configure auto-logon with Sysinternals Autologon. It stores the password" -ForegroundColor Yellow
        Write-Host "           in LSA secrets rather than plaintext registry: Autologon.exe $KioskUser . <password>" -ForegroundColor DarkGray
    }
}

# ================================================================================
# FINALIZATION
# ================================================================================
Write-TSGSection "FINALIZATION"

if ($SkippedEntControls.Count -gt 0) {
    Write-Host ""
    Write-Host "  Enterprise-only controls skipped on this Pro SKU:" -ForegroundColor Yellow
    $SkippedEntControls | ForEach-Object { Write-Host "    * $_" -ForegroundColor Yellow }
    Write-Host "  Source: learn.microsoft.com/windows/security/licensing-and-edition-requirements" -ForegroundColor DarkGray
}

Write-Host ""
Write-Host "  Kiosk lockdown complete." -ForegroundColor DarkYellow
Write-Host "  Log: $LogPath" -ForegroundColor Gray
Write-Host "  RESTART REQUIRED: DEP, LSA Protection, IPv6 preference, Credential Guard, BitLocker, removable storage policy" -ForegroundColor Yellow
Write-Host ""
Write-Host "  POST-RESTART CHECKLIST:" -ForegroundColor Gray
Write-Host "    1. Log on as the kiosk account and confirm the app launches as the shell with no Explorer" -ForegroundColor DarkGray
Write-Host "    2. Try Ctrl+Alt+Del, Ctrl+Shift+Esc, and Win+R from the kiosk account; all should be inert" -ForegroundColor DarkGray
Write-Host "    3. Insert a USB drive; it must not mount" -ForegroundColor DarkGray
Write-Host "    4. Verify no firewall rules are blocking required connections" -ForegroundColor DarkGray
Write-Host "    5. Review C:\Logs\ for any [FAIL] entries and address them" -ForegroundColor DarkGray
Write-Host "  Hans Study | https://hans.study | contact@hans.study" -ForegroundColor DarkGray

Stop-Transcript | Out-Null

$restart = Read-Host "  Restart now? [y/N]"
if ($restart -match '^[Yy]') {
    Write-Host "  Restarting in 15 seconds. Press Ctrl+C to cancel." -ForegroundColor Yellow
    Start-Sleep -Seconds 15
    Restart-Computer -Force
}
